# TestCaseRefiner module: Refine generated test cases using Mistral.
from __future__ import annotations

import json
import os
from typing import Any

import httpx

from src.step1_extract.models import SelectorMap


class TestCaseRefiner:
    """LLM B: Validate and enrich generated test cases using Mistral."""

    def __init__(
        self,
        *,
        model: str | None = None,
        timeout: float = 30.0,
    ):
        """
        Initialize the refiner.

        Args:
            model: Mistral model name (defaults to STEP2_MODEL env var or "mistral-medium-latest")
            timeout: Request timeout in seconds
        """
        self.model = model or os.getenv("STEP2_MODEL", "mistral-medium-latest")
        self.timeout = timeout

    async def refine(
        self,
        *,
        objective: str,
        selector_map: SelectorMap,
        generated_payload: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Refine test cases using Mistral.

        Args:
            objective: User's test objective
            selector_map: Available selectors from Step 1
            generated_payload: Initial test cases generated by LLM A

        Returns:
            Dict with "cases" list containing refined test cases
        """
        prompt = self._build_prompt(
            objective=objective,
            selector_map=selector_map,
            generated_payload=generated_payload,
        )

        errors: list[str] = []

        primary_key = os.getenv("MISTRAL_API_KEY", "").strip()
        if primary_key:
            try:
                raw_response = await self._call_mistral(prompt=prompt, api_key=primary_key)
                text = self._extract_response_text(raw_response)
                return self._parse_mistral_json(text)
            except Exception as exc:
                errors.append(f"mistral failed: {exc}")
        else:
            errors.append("mistral skipped: missing MISTRAL_API_KEY")

        fallback_key = os.getenv("GEMINI_API_KEY", "").strip()
        if not fallback_key:
            errors.append("gemini skipped: missing GEMINI_API_KEY")
            raise RuntimeError("Step 2 refinement failed after fallback: " + " | ".join(errors))

        try:
            raw_response = await self._call_gemini(prompt=prompt, api_key=fallback_key)
            text = self._extract_gemini_text(raw_response)
            return self._parse_mistral_json(text)
        except Exception as exc:
            errors.append(f"gemini failed: {exc}")
            raise RuntimeError("Step 2 refinement failed after fallback: " + " | ".join(errors))

    def _build_prompt(
        self,
        *,
        objective: str,
        selector_map: SelectorMap,
                generated_payload: dict[str, Any],
    ) -> str:
                """Build prompt for Mistral validator/enricher with generated cases and selector map."""
                selector_payload = [
                        {
                                "selector_id": r.selector_id,
                                "selector": r.selector,
                                "kind": r.kind.value,
                                "llm_role": r.llm_role,
                                "label": r.label,
                                "placeholder": r.placeholder,
                                "text": r.text,
                                "is_fragile": r.is_fragile,
                                "suggested_selector": r.suggested_selector,
                        }
            for r in selector_map.records
                ]

                return (
                        "You are an expert QA reviewer.\n"
                        "Validate and enrich the provided generated test cases.\n"
                        "Check logical coherence, selector existence, and realism against page structure.\n"
                        "You may reorder steps, remove redundant steps, or remove invalid cases.\n"
                        "Return STRICT JSON only (no markdown).\n\n"
                        f"OBJECTIVE:\n{objective}\n\n"
                        f"SELECTOR_MAP_JSON:\n{json.dumps(selector_payload, ensure_ascii=True)}\n\n"
                        f"GENERATED_CASES_JSON:\n{json.dumps(generated_payload, ensure_ascii=True)}\n\n"
                        "OUTPUT_SCHEMA:\n"
                        "{\n"
                        '  "cases": [\n'
                        "    {\n"
                        '      "test_id": "str",\n'
                        '      "objective": "str",\n'
                        '      "steps": [\n'
                        "        {\n"
                        '          "step_id": "str",\n'
                        '          "action": "click|type|press|wait|assert_text|assert_visible",\n'
                        '          "selector_id": "str or null",\n'
                        '          "value": "str or null",\n'
                        '          "timeout_ms": 10000,\n'
                        '          "notes": "str or null"\n'
                        "        }\n"
                        "      ]\n"
                        "    }\n"
                        "  ],\n"
                        '  "invalid_cases": [\n'
                        "    {\n"
                        '      "test_id": "str",\n'
                        '      "reason": "str"\n'
                        "    }\n"
                        "  ]\n"
                        "}\n"
                )

    async def _call_mistral(self, *, prompt: str, api_key: str) -> dict:
        """Call Mistral API."""
        async with httpx.AsyncClient(timeout=self.timeout) as client:
            response = await client.post(
                "https://api.mistral.ai/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": self.model,
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0,
                    "response_format": {"type": "json_object"},
                },
            )
            response.raise_for_status()
            return response.json()

    async def _call_gemini(self, *, prompt: str, api_key: str) -> dict:
        model = os.getenv("STEP2_REFINER_FALLBACK_MODEL", "gemini-2.5-flash")
        endpoint = (
            f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"
            f"?key={api_key}"
        )
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": 0,
                "responseMimeType": "application/json",
            },
        }

        async with httpx.AsyncClient(timeout=self.timeout) as client:
            response = await client.post(endpoint, json=payload)
            response.raise_for_status()
            return response.json()

    def _extract_response_text(self, raw_response: dict) -> str:
        """Extract text from Mistral response structure."""
        try:
            return raw_response["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as e:
            raise ValueError(f"Failed to extract text from Mistral response: {e}")

    def _extract_gemini_text(self, raw_response: dict) -> str:
        try:
            return raw_response["candidates"][0]["content"]["parts"][0]["text"]
        except (KeyError, IndexError, TypeError) as e:
            raise ValueError(f"Failed to extract text from Gemini response: {e}")

    def _parse_mistral_json(self, text: str) -> dict:
        """Parse JSON response, handling markdown code block wrappers."""
        text = text.strip()

        # Remove markdown code blocks if present
        if text.startswith("```"):
            lines = text.split("\n")
            text = "\n".join(
                line for line in lines[1:-1] if not line.startswith("```")
            )

        parsed = json.loads(text)

        if not isinstance(parsed, dict):
            raise ValueError(f"Expected root JSON object, got {type(parsed).__name__}")

        if "cases" not in parsed:
            raise ValueError("Response missing 'cases' key")

        if not isinstance(parsed["cases"], list):
            raise ValueError(f"Expected 'cases' to be list, got {type(parsed['cases']).__name__}")

        return parsed
